name: 'blender'
save:
    folder: './results'
arch:
    max_epochs: 100
checkpoint:
    save_top_k: 10
    monitor: 'abs_rel_pp_gt'
    monitor_index: 0
model:
    name: 'SupModelMF'
    optimizer:
        name: 'Adam'
        depth:
            lr: 0.0002
        pose:
            lr: 0.0002
    scheduler:
        name: 'StepLR'
        step_size: 30
        gamma: 0.5
    depth_net:
        name: 'DepthPoseNet'
        version: 'it12-h-out'
    loss: 
        automask_loss: True
        photometric_reduce_op: 'min'
    params:
        crop: ''
        min_depth: 0.001
        max_depth: 100.0
    flow_net:
        mode: "depth"
        dataset: "blrnder"
        num_scales: 2
        depth_match_num: 6000
        depth_sample_ratio: 0.20
        depth_scale: 1
        w_ssim: 0.85 # w_pixel = 1 - w_ssim
        w_flow_smooth: 10.0
        w_flow_consis: 0.01
        w_geo: 1.0
        w_pt_depth: 1.0
        w_pj_depth: 0.1
        w_flow_error: 0.0
        w_depth_smooth: 0.001
        h_flow_consist_alpha: 3.0
        h_flow_consist_beta: 0.05
        ransac_iters: 100
        ransac_points: 6000
datasets:
    augmentation:
        image_shape: (320, 320)
    train:
        batch_size: 2
        dataset: ['Blender']
        path: ['E:/DataSet/blender/train']
        split: ['']
        depth_type: ['velodyne']
        repeat: [1]
        forward_context: 2
        back_context: 0
        num_workers: 1
    validation:
        dataset: ['Blender']
        path: ['E:/DataSet/blender/test']
        split: ['']
        depth_type: ['velodyne']
        forward_context: 1
        back_context: 1
    test:
        dataset: ['Blender']
        path: ['E:/DataSet/blender/test']
        split: ['']
        depth_type: ['velodyne']
        forward_context: 1
        back_context: 0
